### ISSUE TITLE
Can not run inference

### ISSUE THREAD

**Issue by rk-helper** [JueLin/textureSynthesis-stylegan2-pytorch#1]
Hello! I'm trying to run the paper and pretained pt model with the following command 

`!python inference.py --n_textures 500 --samples_per_texture 10 --image_size 1024 --load_ckpt "/content/drive/MyDrive/Texture Synthesis/300000.pt" --output "/content/drive/MyDrive/Texture Synthesis"`

However, I got the error:

```
Loading texture model from /content/drive/MyDrive/Texture Synthesis/300000.pt:
Traceback (most recent call last):
  File "inference.py", line 45, in <module>
    generator.load_state_dict(ckpt["g_ema"])
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1483, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for MultiScaleTextureGenerator:
	Missing key(s) in state_dict: "convs.12.conv.weight", "convs.12.conv.blur.kernel", "convs.12.conv.modulation.weight", "convs.12.conv.modulation.bias", "convs.12.noise.weight", "convs.12.activate.bias", "convs.13.conv.weight", "convs.13.conv.modulation.weight", "convs.13.conv.modulation.bias", "convs.13.noise.weight", "convs.13.activate.bias", "convs.14.conv.weight", "convs.14.conv.blur.kernel", "convs.14.conv.modulation.weight", "convs.14.conv.modulation.bias", "convs.14.noise.weight", "convs.14.activate.bias", "convs.15.conv.weight", "convs.15.conv.modulation.weight", "convs.15.conv.modulation.bias", "convs.15.noise.weight", "convs.15.activate.bias", "to_rgbs.6.bias", "to_rgbs.6.upsample.kernel", "to_rgbs.6.conv.weight", "to_rgbs.6.conv.modulation.weight", "to_rgbs.6.conv.modulation.bias", "to_rgbs.7.bias", "to_rgbs.7.upsample.kernel", "to_rgbs.7.conv.weight", "to_rgbs.7.conv.modulation.weight", "to_rgbs.7.conv.modulation.bias", "noises.noise_13", "noises.noise_14", "noises.noise_15", "noises.noise_16". 
```

What I am doing wrong?

**Comment by rk-helper** [comment]
I am not sure, but it is looking like your .pt pretained file does not match to MultiScaleTextureGenerator. Please, could you upload working .pt file to try the inference

**Comment by JueLin** [comment]
Hi there, sorry for the late reply.

I see you are using --image_size 1024. But the uploaded model was trained on 256x256, thus it does not have those state_dict keys (eg convs.12 convs.13..... they are for higher resolution modules, which weren't created when we were training the model)

So you should first initialize the generator with size 256x256, then synthesize 1024x1024. You can do this by providing a list to the --image_size 256, 1024

**Comment by rk-helper** [comment]
thanks! it works

**Comment by JueLin** [comment]
@rk-helper Hi there. Sorry for ping. I am looking for help with a recommendation letter for my immigration petition to United States. A recommendation letter from an independent referer like you is extremely important for an immigration petition and I sincerely hope you can help if you are available. I would like to apologize for the abruptness of this request. I know your time is extremely precious. My immigration case attorney and I can draft a letter for you to save your time. You can feel free to make any changes. Thank you in advance for your time and consideration.
