### ISSUE TITLE
Error loading checkpoint in inference.py

### ISSUE THREAD

**Issue by anderslanglands** [JueLin/textureSynthesis-stylegan2-pytorch#3]
I'm trying to run inference.py using the conda environment you provided (though I had to change `opencv-python` to fastai's `opencv-python-headless==4.5.5.64` as I couldn't find a matching `opencv-python` version on any channel). I'm on Ubuntu 20.04 with CUDA 11.1.

Running:
```bash
python inference.py --device cuda --input PavingStones111_512_Color.png --output paving512_01.png --image_size 512 --model_name texture --load_ckpt ./300000.pt
```

Gives me:
```bash
Loading texture model from ./300000.pt:
Traceback (most recent call last):
  File "inference.py", line 45, in <module>
    generator.load_state_dict(ckpt["g_ema"])
  File "/home/anders/miniconda3/envs/texture-synthesis-jlin22/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1406, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for MultiScaleTextureGenerator:
        Missing key(s) in state_dict: "convs.12.conv.weight", "convs.12.conv.blur.kernel", "convs.12.conv.modulation.weight", "convs.12.conv.modulation.bias", "convs.12.noise.weight", "convs.12.activate.bias", "convs.13.conv.weight", "convs.13.conv.modulation.weight", "convs.13.conv.modulation.bias", "convs.13.noise.weight", "convs.13.activate.bias", "to_rgbs.6.bias", "to_rgbs.6.upsample.kernel", "to_rgbs.6.conv.weight", "to_rgbs.6.conv.modulation.weight", "to_rgbs.6.conv.modulation.bias", "noises.noise_13", "noises.noise_14".
```

Any ideas?

**Comment by JueLin** [comment]
Hi there,

Thank you for your interest in the repo. I noticed two things here:
1. you have the --input PavingStones111_512_Color.png, the "--input" argument should be a latent vector instead of an image file, and the "--output" argument should be a directory. (I probably should have documented that more carefully....)
2.  This is related to the error message. Please see #1 for the discussion. Let me know if it makes sense or not.

**Comment by anderslanglands** [comment]
Thanks for your quick reply! Please excuse my ignorance here I'm new to this, 2) makes sense but for 1) How do I create a latent vector to feed the input?

**Comment by JueLin** [comment]
The "--input" argument is mainly for reproducibility. As you can see in inference.py line 69, we also save the latent vector alongside the generated textures. So when you generate a whole bunch of textures and find one that is interesting to you, you can use that corresponding latent vector to reproduce that texture.

**Comment by JueLin** [comment]
And forgot to mention, you can generate textures without the input argument. In this case, the multivariate IID gaussian will be sampled.

**Comment by anderslanglands** [comment]
Got it working now, thanks! So if I wanted to generate a bunch of textures that looked like a particular exemplar, would I need to retrain the model?

**Comment by JueLin** [comment]
Yea our approach is not exemplar based, you need to retrain the model to generate new textures.

**Comment by JueLin** [comment]
@anderslanglands Hi there. Sorry for ping. I am looking for help with a recommendation letter for my immigration petition to United States. A recommendation letter from an independent referer like you is extremely important for an immigration petition and I sincerely hope you can help if you are available.  I would like to apologize for the abruptness of this request. I know your time is extremely precious. My immigration case attorney and I can draft a letter for you to save your time. You can feel free to make any changes. Thank you in advance for your time and consideration.
